### ISSUE TITLE
Change possible moves to ArrayList?

### ISSUE THREAD

**Issue by updbqn** [Absurdius/Reversi#2]
https://github.com/Absurdius/Reversi/blob/7bc0ef8467966ad2ff9338849c4aaa6b4fb8eb9e/Reversi/src/game/Game.java#L60

Fritt fram att ändra datastrukturer jämfört med det vi pratade om innan, jag anpassar mig!

`ArrayList<Integer[]>` här kanske. Så slipper vi oroa oss för antal moves och vi slipper kolla när resten bara är skräp?

Eller skapa en `Move` klass om det gör saker lättare och kör `ArrayList<Move>`?

**Comment by Absurdius** [comment]
låter ok, ska ta itu med det
